//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.11 at 07:56:18 PM MSK 
//


package org.alfresco.model.dictionary._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for childAssociation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="childAssociation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.alfresco.org/model/dictionary/1.0}association"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="child-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="duplicate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="propagateTimestamps" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "childAssociation", propOrder = {
    "childName",
    "duplicate",
    "propagateTimestamps"
})
public class ChildAssociation
    extends Association
{

    @XmlElement(name = "child-name")
    protected String childName;
    protected Boolean duplicate;
    protected Boolean propagateTimestamps;

    /**
     * Gets the value of the childName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildName() {
        return childName;
    }

    /**
     * Sets the value of the childName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildName(String value) {
        this.childName = value;
    }

    /**
     * Gets the value of the duplicate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDuplicate() {
        return duplicate;
    }

    /**
     * Sets the value of the duplicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDuplicate(Boolean value) {
        this.duplicate = value;
    }

    /**
     * Gets the value of the propagateTimestamps property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPropagateTimestamps() {
        return propagateTimestamps;
    }

    /**
     * Sets the value of the propagateTimestamps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPropagateTimestamps(Boolean value) {
        this.propagateTimestamps = value;
    }

}
