//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.11 at 07:56:18 PM MSK 
//


package org.alfresco.model.dictionary._1;



/**
 * Interface generated from group/attributeGroup declaration:
 * {http://www.alfresco.org/model/dictionary/1.0}name
 * Schema document "file:/D:/projects/neodoc/tools/eclipse/oxygen/alfresco-dictionary-schema/src/main/resources/modelSchema.xsd", line 332, column 35
 * The following schema fragment is represented by this interface:
 * <pre>
 * &lt;attGroup name="name"&gt;
 *   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 * &lt;/attGroup&gt;
 * </pre>
 * 
 */
public interface Name {


    String getName();

    void setName(String value);

}
