//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.28 at 06:00:48 PM MSK 
//


package ru.neodoc.modeller.extensions;



/**
 * Interface generated from group/attributeGroup declaration:
 * {http://neodoc.ru/modeller/extensions}named
 * Schema document "file:/D:/projects/neodoc/tools/eclipse/oxygen/modeller-extensions-schema/src/main/resources/modellerExtensions.xsd", line 25, column 34
 * The following schema fragment is represented by this interface:
 * <pre>
 * &lt;attGroup name="named"&gt;
 *   &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 * &lt;/attGroup&gt;
 * </pre>
 * 
 */
public interface Named {


    String getName();

    void setName(String value);

}
