//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.28 at 06:00:48 PM MSK 
//


package ru.neodoc.modeller.extensions;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for umlObjectReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="umlObjectReference"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attGroup ref="{http://neodoc.ru/modeller/extensions}umlRef"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "umlObjectReference")
public class UmlObjectReference
    implements UmlRef
{

    @XmlAttribute(name = "umlId")
    protected String umlId;
    @XmlAttribute(name = "umlName")
    protected String umlName;

    /**
     * Gets the value of the umlId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmlId() {
        return umlId;
    }

    /**
     * Sets the value of the umlId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmlId(String value) {
        this.umlId = value;
    }

    /**
     * Gets the value of the umlName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUmlName() {
        return umlName;
    }

    /**
     * Sets the value of the umlName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUmlName(String value) {
        this.umlName = value;
    }

}
